// VSCode extentions REST client
// You may use other REST api tester tools (Thunder Client stc..)

#### Test
GET http://localhost:8004/api/test HTTP/1.1

#### GET all
GET http://localhost:8004/api/articles HTTP/1.1

#### GET single
GET http://localhost:8004/api/articles/1 HTTP/1.1

#### POST invalid nontents
POST http://localhost:8004/api/articles HTTP/1.1
Content-Type: application/json

{
    "userName": "Test User 1",
    "gameName": "",
    "profile": "Test User Profile",
    "schedule": [],
    "meal_description": "エナドリガンガン飲みます。",
    "notice": ""
}

#### POST valid nontents
POST http://localhost:8004/api/articles HTTP/1.1
Content-Type: application/json

{
    "userName": "Test UserName 1",
    "gameName": "Test GameName 1",
    "profile": "Test User Profile",
    "schedule": [
        {
            "menu": "Valorant",
            "start_time": "8",
            "end_time": "12"
        },
        {
            "menu": "ご飯",
            "start_time": "12",
            "end_time": "13"
        }
    ],
    "meal_description": "エナドリガンガン飲みます。",
    "notice": "Test Notice"
}

#### PUT invalid nontents
PUT http://localhost:8004/api/articles/1 HTTP/1.1
Content-Type: application/json

{
    "userName": "updated article",
    "gameName": ""
}

#### PUT valid nontents
PUT http://localhost:8004/api/articles/1 HTTP/1.1
Content-Type: application/json

{
    "userName": "updated userName",
    "gameName": "update gameName",
    "schedule": [
        {
            "menu": "Pokemon",
            "start_time": "12",
            "end_time": "19"
        }
    ]
}

#### DELETE
DELETE http://localhost:8004/api/articles/2 HTTP/1.1