// VSCode extentions REST client
// You may use other REST api tester tools (Thunder Client stc..)

#### Test
GET http://localhost:8004/api/test HTTP/1.1

#### GET all
GET http://localhost:8004/api/articles HTTP/1.1

#### GET single
GET http://localhost:8004/api/articles/1 HTTP/1.1

#### POST not contents
POST http://localhost:8004/api/articles HTTP/1.1
Content-Type: application/json

#### POST with nontents
POST http://localhost:8004/api/articles HTTP/1.1
Content-Type: application/json

{
  "name": "Test User"
}

#### PUT
PUT http://localhost:8004/api/articles/1 HTTP/1.1
Content-Type: application/json

{
  "name": "updated article"
}

#### DELETE
DELETE http://localhost:8004/api/articles/1 HTTP/1.1